name: Release Solution Template
# Reusable workflow
# convert solution to managed (using a build PowerPlatform environment for the conversion)
# upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  workflow_call:
    inputs: 
      #Do Not change these values
      #Values are set by the caller
      #caller sample: release-action-call.ymnl
      SOLUTION_NAME:
        description: 'The solution name.'
        type: string
        required: true       
      SOLUTION_SHIPPING_FOLDER:
        description: 'folder name for staging the exported solution *do not change*'        
        type: string
        default: out/ship/
      SOLUTION_OUTBOUND_FOLDER:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        default: out/solutions/
      SOLUTION_SOURCE_FOLDER: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       default: solutions/
      SOLUTION_RELEASE_FOLDER:
       description: 'folder where the released binaries are going to be hosted *do not change*'
       type: string
       default: out/release   
      CLOUD_TYPE: 
        description: 'The cloud type (Public, UsGov, UsGovHigh, UsGovDoD)'
        type: string
        required: true
    secrets:
      AAD_APP_SECRET:
        description: 'The secret of the AAD application for authentication'
        required: true
      AAD_CLIENT_ID:
        description: 'The client ID of the AAD application for authentication'
        required: true
      AAD_TENANT_ID:
        description: 'The tenant ID of the AAD application for authentication'
        required: true
      BUILD_ENVIRONMENT_URL:
        description: 'Build environment url.'
        required: true      
      PRODUCTION_ENVIRONMENT_URL: 
        description: 'Production environment url.'
        required: true  

jobs:
  convert-to-managed:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ inputs.SOLUTION_SOURCE_FOLDER}}/${{ inputs.SOLUTION_NAME }}
        solution-file: ${{ inputs.SOLUTION_OUTBOUND_FOLDER}}/${{ inputs.SOLUTION_NAME }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{secrets.BUILD_ENVIRONMENT_URL}}
        app-id: ${{ secrets.AAD_CLIENT_ID }}
        client-secret: ${{ secrets.AAD_APP_SECRET }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        cloud: ${{inputs.CLOUD_TYPE}}
        solution-file: ${{ inputs.SOLUTION_OUTBOUND_FOLDER}}/${{ inputs.SOLUTION_NAME }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{secrets.BUILD_ENVIRONMENT_URL}}
        app-id: ${{ secrets.AAD_CLIENT_ID }}
        client-secret: ${{ secrets.AAD_APP_SECRET }} 
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        cloud: ${{inputs.CLOUD_TYPE}}
        solution-name: ${{ inputs.SOLUTION_NAME }}
        managed: true
        solution-output-file: ${{ inputs.SOLUTION_SHIPPING_FOLDER}}/${{ inputs.SOLUTION_NAME }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ inputs.SOLUTION_SHIPPING_FOLDER}}/${{ inputs.SOLUTION_NAME }}.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ inputs.SOLUTION_RELEASE_FOLDER}}
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{secrets.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{ secrets.AAD_CLIENT_ID }}
        client-secret: ${{ secrets.AAD_APP_SECRET }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        cloud: ${{inputs.CLOUD_TYPE}}
        solution-file: ${{ inputs.SOLUTION_RELEASE_FOLDER}}/${{ inputs.SOLUTION_NAME }}.zip
        force-overwrite: true
        publish-changes: true